//Arpan Parikh 2016A7TS0082
//Pranav Panchumarthi 2017A7PS0153
//Asrita V. Mandalam 2017A7PS1179
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include "lexer.c"
#include "grammar.c"
#include "newparser.c"
#include "ast.c"
#include "symboltable.c"
#include "codegen.c"
int main(int argc, char * argv[])
{
	clock_t startTime, endTime;
	double CpuTime, CpuSeconds;
	startTime = clock();	
	FILE *fp;
	fp= fopen(argv[1], "r");
	FILE *filePointer;
	while(1)
	{
		int op;
		printf("\n\nCOMPILERS PROJECT MENU\n");
		printf("0: Exit\n");
		printf("1. Print token list generated by lexer\n");
		printf("2. Produce parse tree (on console)\n");
		printf("3. Print Abstract Syntax Tree\n");
		printf("4. Amount of allocated memory, number of nodes for Parse Tree and AST\n");
		printf("5. Print Symbol Table\n");
		printf("6. Print Activation Record Size\n");
		printf("7. Print Static and Dynamic Arrays\n");
		printf("8. Print Error Repot and total compile time\n");
		printf("9. Code Generation\n");
		scanf("%d",&op);
		if((op!=1)&&(op!=0))
		{
			//THE FUNCTION FROM LEXER
		}
		switch(op)
		{
			struct symTable tab;
			struct symTable* s;
			case 0: return(0);
					break;
			case 1: 
					filePointer = fopen("t1.txt", "r");
					tokenize(filePointer);
					break;
			case 2: 
					filePointer = fopen("t1.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					generateptree();
					printtree();
					//fclose(filePointer);	
					break;	
			case 3: 
					filePointer = fopen("t1.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					generateptree();
					mainast = makeast(tr,NULL);
					break;	
			case 4:
					filePointer = fopen("t1.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					generateptree();
					mainast = makeast(tr,NULL);
					printf("Number of Parse Tree Nodes: %d\n",numparsernodes);
					printf("Number of AST nodes:        %d\n",numastnodes);
					float compratio = (numastnodes/1.0f)/(numparsernodes/1.0f);
					compratio = (1.0-compratio) * 100.0;
					printf("Compression ratio:          %f",compratio);
					break;
			case 5:	
					filePointer = fopen("c10.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					generateptree();
					mainast = makeast(tr,NULL);				
					s = &tab;
					semanalyzer(mainast,s);
					for(int i=0;i<100;i++)
					{
						if(variables[i] == NULL)
							break;
						printf("%s\t%d\t%d\t%s\t%d\t%d\n",variables[i]->name, variables[i]->offset,variables[i]->type,variables[i]->scope,variables[i]->lower,variables[i]->upper);
					}
					//fclose(filePointer);	
					break;
			case 6:
					filePointer = fopen("t1.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					generateptree();
					mainast = makeast(tr,NULL);				
					s = &tab;
					semanalyzer(mainast,s);
					for(int i=0;i<100;i++)
					{
						if(symlist[i] == NULL)
							break;
						printf("%s\t%d\n",symlist[i]->name, symlist[i]->offset);
					}
					//fclose(filePointer);	
					break;
			case 7:
					filePointer = fopen("c8.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					printparsetable();
					generateptree();
					mainast = makeast(tr,NULL);				
					s = &tab;
					semanalyzer(mainast,s);
					for(int i=0;i<100;i++)
					{
						if(arrays[i] == NULL)
							break;
						printf("%s\t%d\t%d\t%s\t%d\t%d\n",arrays[i]->name, arrays[i]->offset,arrays[i]->type,arrays[i]->scope,arrays[i]->lower,arrays[i]->upper);
					}
					//fclose(filePointer);	
					break;
			case 8:
					filePointer = fopen("t1.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					generateptree();
					mainast = makeast(tr,NULL);				
					s = &tab;
					semanalyzer(mainast,s);
					for(int i=0;i<100;i++)
					{
						if(erlist[i] == NULL)
							break;
						printf("%s\t%d\t%d\n",erlist[i]->text, erlist[i]->no,erlist[i]->lineno);
					}
					//fclose(filePointer);	
					break;
			case 9:
					filePointer = fopen("t1.txt", "r");
					tokenize(filePointer);
					populategrammar();
    				generateparsetable();
					generateptree();
					mainast = makeast(tr,NULL);				
					s = &tab;
					semanalyzer(mainast,s);
					codegenerator(mainast,s,datafp);
					//fclose(filePointer);	
					break;
			default: printf("Invalid option number. Try again\n");
		}
	}
	endTime = clock();
	CpuTime  =  (double) (endTime - startTime);
	CpuSeconds =   CpuTime / CLOCKS_PER_SEC;
	printf("Total CPU time elapsed: %d\n",CpuTime);
	printf("Total CPU time elapsed in seconds: %d\n",CpuSeconds);
	return 0;
}